name: ICT Meetup Admin Panel CI/CD

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build static site
        run: yarn build
        env:
          CI: false
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 91.204.209.27
          username: ${{ secrets.FTP_DEV_USERNAME }}
          password: ${{ secrets.FTP_DEV_PASSWORD }}
          local-dir: ./dist/
          protocol: ftps
          port: 21
          timeout: 60000
